import type { Metadata } from "next";
import Link from "next/link";
import { Check, Minus } from "@phosphor-icons/react/ssr";
import { PageIntro } from "@/components/page-intro";
import { PricingPlans } from "@/components/pricing-plans";
import { Faq } from "@/components/faq";
import { Reveal } from "@/components/reveal";

export const metadata: Metadata = {
  title: "Pricing",
  description: "Solder is free for personal projects. Pro and Team add unlimited AI, preview environments and admin controls.",
};

type Cell = boolean | string;

// mock: placeholder plan limits, keep in sync with pricing-plans.tsx
const COMPARE: { group: string; rows: [string, Cell, Cell, Cell][] }[] = [
  {
    group: "Editor",
    rows: [
      ["Native editor, debugger and Git", true, true, true],
      ["Database, HTTP and container panels", true, true, true],
      ["Community plugins", true, true, true],
      ["Settings sync", false, true, true],
    ],
  },
  {
    group: "Solder AI",
    rows: [
      ["Hosted AI requests", "50 per day", "Unlimited", "Unlimited"],
      ["Your own key or local models", true, true, true],
      ["Agent tasks and AI review", false, true, true],
      ["Shared context and prompts", false, false, true],
    ],
  },
  {
    group: "Ship",
    rows: [
      ["Preview environments", "1", "10", "Unlimited"],
      ["Seeded database per preview", false, true, true],
    ],
  },
  {
    group: "Admin and support",
    rows: [
      ["SAML SSO and SCIM", false, false, true],
      ["Audit log and usage controls", false, false, true],
      ["Support", "Community", "Email", "Named engineer"],
    ],
  },
];

function Value({ v }: { v: Cell }) {
  if (v === true) return <Check weight="bold" aria-label="Included" className="size-4 text-accent" />;
  if (v === false) return <Minus aria-label="Not included" className="size-4 text-subtle" />;
  return <span className="text-[14px] text-fg">{v}</span>;
}

const FAQ = [
  {
    q: "Is the Hobby plan really free?",
    a: "Yes. The editor, debugger, database tools and plugins are free for personal and open-source work with no time limit. Commercial teams of two or more should use Team.",
  },
  {
    q: "What counts as a hosted AI request?",
    a: "Each chat message, inline edit or review comment generated by a Solder-hosted model is one request. Requests that run on your own API key or a local model are never counted.",
  },
  {
    q: "Does my code leave my machine?",
    a: "Only when you use hosted AI, and only the files needed to answer. Nothing is stored after the response and nothing is used for training. Local models keep everything on your machine.",
  },
  {
    q: "Can I switch between monthly and yearly billing?",
    a: "Any time from your account settings. Switching to yearly applies the discount immediately and credits the rest of your current month.",
  },
  {
    q: "Do you offer self-hosted or on-premises deployments?",
    a: (
      <>
        Yes, for organisations that need a private model gateway or air-gapped installs.{" "}
        <Link href="/contact?topic=sales" className="text-fg underline decoration-accent underline-offset-4">
          Tell us about your setup
        </Link>{" "}
        and we will send details.
      </>
    ),
  },
  {
    q: "Are there discounts for students and open-source maintainers?",
    a: "Pro is free for verified students and for maintainers of open-source projects with active contributors. Apply from the account page after you sign in.",
  },
];

export default function PricingPage() {
  return (
    <>
      <PageIntro
        flora="meadow"
        title="Free to start. Priced per seat after that."
        body="Every plan ships the same native editor. You pay for hosted AI, preview environments and team controls."
      />

      <PricingPlans />

      <section className="mx-auto max-w-[1400px] px-4 py-24 md:px-8 md:py-32">
        <Reveal>
          <h2 className="text-3xl font-semibold tracking-tighter text-fg md:text-4xl">Compare plans</h2>
        </Reveal>

        <Reveal delay={0.06}>
          <div className="mt-10 overflow-x-auto">
            <table className="w-full min-w-[640px] text-left">
              <thead className="sticky top-16 bg-bg">
                <tr className="border-b border-line-strong">
                  <th className="w-[40%] py-4 text-sm font-normal text-subtle">
                    <span className="sr-only">Feature</span>
                  </th>
                  {["Hobby", "Pro", "Team"].map((p) => (
                    <th key={p} className={`py-4 text-[15px] font-medium ${p === "Pro" ? "text-accent" : "text-fg"}`}>
                      {p}
                    </th>
                  ))}
                </tr>
              </thead>
              {COMPARE.map((g) => (
                <tbody key={g.group}>
                  <tr>
                    <th colSpan={4} className="pb-3 pt-10 text-sm font-medium text-fg">
                      {g.group}
                    </th>
                  </tr>
                  {g.rows.map(([label, ...vals]) => (
                    <tr key={label}>
                      <td className="py-2.5 pr-6 text-[15px] text-muted">{label}</td>
                      {vals.map((v, i) => (
                        <td key={i} className="py-2.5">
                          <Value v={v} />
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              ))}
            </table>
          </div>
        </Reveal>
      </section>

      <section className="border-t border-line">
        <div className="mx-auto grid max-w-[1400px] gap-10 px-4 py-24 md:px-8 md:py-32 lg:grid-cols-[minmax(0,4fr)_minmax(0,8fr)] lg:gap-16">
          <Reveal>
            <h2 className="text-3xl font-semibold tracking-tighter text-fg md:text-4xl">Questions, answered</h2>
          </Reveal>
          <Reveal delay={0.06}>
            <Faq items={FAQ} />
          </Reveal>
        </div>
      </section>
    </>
  );
}
